### ISSUE TITLE
Add a Pathfinding view/Improve Simulation view

### ISSUE THREAD

**Issue by Mardelor** [outech-robotic/code#68]
It would be nice to show graph's representation or even computed paths on the simulation view in the `outech-debug` tool. Should it be a new view (new route) or should it be integrated into the simulation view ? Maybe with a `checkbox` option ?

**Comment by tictacmenthe** [comment]
If its just a few lines we could easily add it to the simulation view.
Maybe only show the next few straight lines, or show  them all but with a very small width of lines ?
